management.context.thread.enable: true
rcn:
  events.enable: true
  message:
    brokers:
      standalone:
        enable: true
secrets:
  provider:
    vault:
      enable: true
      addr: "https://vault.internal.iorcloud.co.in/"
app:
  channels:
    telegram:
      token: "vault://secrets/iorcloud agentic bot_token"
      default_chat_id: "vault://secrets/iorcloud agentic chat_id"
  tavily:
    api_key: "vault://secrets/iorcloud agentic tavily_api_key"
  agentic:
    config_path: resources/agentic.json