management.context.thread.enable: true
rcn:
  events.enable: true
  message:
    brokers:
      standalone:
        enable: true
secrets.provider.env.enable: true
app:
  channels:
    telegram:
      token: "env://TELEGRAM_BOT_TOKEN"
      default_chat_id: "env://TELEGRAM_DEFAULT_CHAT_ID"
  tavily:
    api_key: "env://TAVILY_API_KEY"
  agentic:
    config_path: resources/agentic.json